/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedUserRouteImport } from './routes/_protected/user'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBorrowRecordsRouteImport } from './routes/_protected/borrow-records'
import { Route as ProtectedBorrowApplicationRouteImport } from './routes/_protected/borrow-application'
import { Route as ProtectedAddBookRouteImport } from './routes/_protected/add-book'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedUserRoute = ProtectedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedBorrowRecordsRoute = ProtectedBorrowRecordsRouteImport.update({
  id: '/borrow-records',
  path: '/borrow-records',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedBorrowApplicationRoute =
  ProtectedBorrowApplicationRouteImport.update({
    id: '/borrow-application',
    path: '/borrow-application',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAddBookRoute = ProtectedAddBookRouteImport.update({
  id: '/add-book',
  path: '/add-book',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/add-book': typeof ProtectedAddBookRoute
  '/borrow-application': typeof ProtectedBorrowApplicationRoute
  '/borrow-records': typeof ProtectedBorrowRecordsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/user': typeof ProtectedUserRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/add-book': typeof ProtectedAddBookRoute
  '/borrow-application': typeof ProtectedBorrowApplicationRoute
  '/borrow-records': typeof ProtectedBorrowRecordsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/user': typeof ProtectedUserRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_protected/add-book': typeof ProtectedAddBookRoute
  '/_protected/borrow-application': typeof ProtectedBorrowApplicationRoute
  '/_protected/borrow-records': typeof ProtectedBorrowRecordsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/user': typeof ProtectedUserRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/signup'
    | '/add-book'
    | '/borrow-application'
    | '/borrow-records'
    | '/dashboard'
    | '/user'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/signup'
    | '/add-book'
    | '/borrow-application'
    | '/borrow-records'
    | '/dashboard'
    | '/user'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/signup'
    | '/_protected/add-book'
    | '/_protected/borrow-application'
    | '/_protected/borrow-records'
    | '/_protected/dashboard'
    | '/_protected/user'
    | '/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/user': {
      id: '/_protected/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof ProtectedUserRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/borrow-records': {
      id: '/_protected/borrow-records'
      path: '/borrow-records'
      fullPath: '/borrow-records'
      preLoaderRoute: typeof ProtectedBorrowRecordsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/borrow-application': {
      id: '/_protected/borrow-application'
      path: '/borrow-application'
      fullPath: '/borrow-application'
      preLoaderRoute: typeof ProtectedBorrowApplicationRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/add-book': {
      id: '/_protected/add-book'
      path: '/add-book'
      fullPath: '/add-book'
      preLoaderRoute: typeof ProtectedAddBookRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedAddBookRoute: typeof ProtectedAddBookRoute
  ProtectedBorrowApplicationRoute: typeof ProtectedBorrowApplicationRoute
  ProtectedBorrowRecordsRoute: typeof ProtectedBorrowRecordsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedUserRoute: typeof ProtectedUserRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAddBookRoute: ProtectedAddBookRoute,
  ProtectedBorrowApplicationRoute: ProtectedBorrowApplicationRoute,
  ProtectedBorrowRecordsRoute: ProtectedBorrowRecordsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedUserRoute: ProtectedUserRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
