/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedRenewalRecordsRouteImport } from './routes/_protected/renewal-records'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBorrowRecordsRouteImport } from './routes/_protected/borrow-records'
import { Route as ProtectedBorrowApplicationRouteImport } from './routes/_protected/borrow-application'
import { Route as ProtectedUserRouteRouteImport } from './routes/_protected/_user/route'
import { Route as ProtectedLimitsRouteRouteImport } from './routes/_protected/_limits/route'
import { Route as ProtectedUserUserRouteImport } from './routes/_protected/_user/user'
import { Route as ProtectedLimitsAddBookRouteImport } from './routes/_protected/_limits/add-book'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedRenewalRecordsRoute = ProtectedRenewalRecordsRouteImport.update({
  id: '/renewal-records',
  path: '/renewal-records',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedBorrowRecordsRoute = ProtectedBorrowRecordsRouteImport.update({
  id: '/borrow-records',
  path: '/borrow-records',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedBorrowApplicationRoute =
  ProtectedBorrowApplicationRouteImport.update({
    id: '/borrow-application',
    path: '/borrow-application',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedUserRouteRoute = ProtectedUserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLimitsRouteRoute = ProtectedLimitsRouteRouteImport.update({
  id: '/_limits',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUserUserRoute = ProtectedUserUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProtectedUserRouteRoute,
} as any)
const ProtectedLimitsAddBookRoute = ProtectedLimitsAddBookRouteImport.update({
  id: '/add-book',
  path: '/add-book',
  getParentRoute: () => ProtectedLimitsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/borrow-application': typeof ProtectedBorrowApplicationRoute
  '/borrow-records': typeof ProtectedBorrowRecordsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/renewal-records': typeof ProtectedRenewalRecordsRoute
  '/auth/login': typeof AuthLoginRoute
  '/add-book': typeof ProtectedLimitsAddBookRoute
  '/user': typeof ProtectedUserUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/borrow-application': typeof ProtectedBorrowApplicationRoute
  '/borrow-records': typeof ProtectedBorrowRecordsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/renewal-records': typeof ProtectedRenewalRecordsRoute
  '/auth/login': typeof AuthLoginRoute
  '/add-book': typeof ProtectedLimitsAddBookRoute
  '/user': typeof ProtectedUserUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_protected/_limits': typeof ProtectedLimitsRouteRouteWithChildren
  '/_protected/_user': typeof ProtectedUserRouteRouteWithChildren
  '/_protected/borrow-application': typeof ProtectedBorrowApplicationRoute
  '/_protected/borrow-records': typeof ProtectedBorrowRecordsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/renewal-records': typeof ProtectedRenewalRecordsRoute
  '/auth/login': typeof AuthLoginRoute
  '/_protected/_limits/add-book': typeof ProtectedLimitsAddBookRoute
  '/_protected/_user/user': typeof ProtectedUserUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/signup'
    | '/borrow-application'
    | '/borrow-records'
    | '/dashboard'
    | '/renewal-records'
    | '/auth/login'
    | '/add-book'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/signup'
    | '/borrow-application'
    | '/borrow-records'
    | '/dashboard'
    | '/renewal-records'
    | '/auth/login'
    | '/add-book'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/signup'
    | '/_protected/_limits'
    | '/_protected/_user'
    | '/_protected/borrow-application'
    | '/_protected/borrow-records'
    | '/_protected/dashboard'
    | '/_protected/renewal-records'
    | '/auth/login'
    | '/_protected/_limits/add-book'
    | '/_protected/_user/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/renewal-records': {
      id: '/_protected/renewal-records'
      path: '/renewal-records'
      fullPath: '/renewal-records'
      preLoaderRoute: typeof ProtectedRenewalRecordsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/borrow-records': {
      id: '/_protected/borrow-records'
      path: '/borrow-records'
      fullPath: '/borrow-records'
      preLoaderRoute: typeof ProtectedBorrowRecordsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/borrow-application': {
      id: '/_protected/borrow-application'
      path: '/borrow-application'
      fullPath: '/borrow-application'
      preLoaderRoute: typeof ProtectedBorrowApplicationRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_user': {
      id: '/_protected/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedUserRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_limits': {
      id: '/_protected/_limits'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLimitsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_user/user': {
      id: '/_protected/_user/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof ProtectedUserUserRouteImport
      parentRoute: typeof ProtectedUserRouteRoute
    }
    '/_protected/_limits/add-book': {
      id: '/_protected/_limits/add-book'
      path: '/add-book'
      fullPath: '/add-book'
      preLoaderRoute: typeof ProtectedLimitsAddBookRouteImport
      parentRoute: typeof ProtectedLimitsRouteRoute
    }
  }
}

interface ProtectedLimitsRouteRouteChildren {
  ProtectedLimitsAddBookRoute: typeof ProtectedLimitsAddBookRoute
}

const ProtectedLimitsRouteRouteChildren: ProtectedLimitsRouteRouteChildren = {
  ProtectedLimitsAddBookRoute: ProtectedLimitsAddBookRoute,
}

const ProtectedLimitsRouteRouteWithChildren =
  ProtectedLimitsRouteRoute._addFileChildren(ProtectedLimitsRouteRouteChildren)

interface ProtectedUserRouteRouteChildren {
  ProtectedUserUserRoute: typeof ProtectedUserUserRoute
}

const ProtectedUserRouteRouteChildren: ProtectedUserRouteRouteChildren = {
  ProtectedUserUserRoute: ProtectedUserUserRoute,
}

const ProtectedUserRouteRouteWithChildren =
  ProtectedUserRouteRoute._addFileChildren(ProtectedUserRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedLimitsRouteRoute: typeof ProtectedLimitsRouteRouteWithChildren
  ProtectedUserRouteRoute: typeof ProtectedUserRouteRouteWithChildren
  ProtectedBorrowApplicationRoute: typeof ProtectedBorrowApplicationRoute
  ProtectedBorrowRecordsRoute: typeof ProtectedBorrowRecordsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedRenewalRecordsRoute: typeof ProtectedRenewalRecordsRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedLimitsRouteRoute: ProtectedLimitsRouteRouteWithChildren,
  ProtectedUserRouteRoute: ProtectedUserRouteRouteWithChildren,
  ProtectedBorrowApplicationRoute: ProtectedBorrowApplicationRoute,
  ProtectedBorrowRecordsRoute: ProtectedBorrowRecordsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedRenewalRecordsRoute: ProtectedRenewalRecordsRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
